### ISSUE TITLE
Create report of spending

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/nixos-foundation#1]
Once we start spending money, we should have a report about how much we are spending and on what, so that people donating money can see what we are using the donations for.

**Comment by sjmackenzie** [comment]
Probably want to take a look at this: http://ledger-cli.org/

**Comment by Baughn** [comment]
So, in light of the recent capacity issues on Hydra, I think this bug has become more important.

This is just anecdotal, but for my own part I haven't set up any kind of donation; my only contributions are in the form of code, and I'm more likely to try running my own Hydra (or pursuing other technical solutions) than to help expand the existing one.

Which is somewhat silly, but it's an inevitable result of not having a public budget, and I don't think I'm alone in this.

So, +1 for fixing that. It'll pay off if you do.

**Comment by grahamc** [comment]
Perhaps an informal note of "this is the sort of stuff we spend money on each month"? To help answer the question: why donate money to the NixOS Foundation?

**Comment by Baughn** [comment]
*Anything* is better than nothing.

At the rate NixOS is expanding, you're going to need a treasurer and rules-compliant ledgering soon enough, but at the moment there's nothing at all.

**Comment by itsN1X** [comment]
@Baughn So, where's the budget? Can I help anyhow?

**Comment by Baughn** [comment]
@itsN1X I'm not on the core team. You're asking the wrong guy.

@grahamc?

**Comment by itsN1X** [comment]
Umm.. @grahamc ? @garbas ?

**Comment by grahamc** [comment]
Not me! :)

**Comment by itsN1X** [comment]
@domenkozar ?

**Comment by domenkozar** [comment]
Yeah me :(

**Comment by rbvermaa** [comment]
@domenkozar Any chance you'll be able to work on it this week or so? Remember, no is also an answer ;-)

**Comment by itsN1X** [comment]
I'm kinda free this week till uni starts in full swing, and could commit some time to this project. @domenkozar add me to the crew?

**Comment by grahamc** [comment]
Hey @itsN1X, unfortunately there are probably three people in this world capable of doing this ticket, and two of them are already here. I've noticed you around, asking to be added to the NixOS organization. For what its worth, that usually only happens after a long history of consistent and quality contributions to the NixOS/nixpkgs project. Just thought I'd let you know. It is great having new and enthusiastic NixOS users in our community!

**Comment by itsN1X** [comment]
Umm, okay, is there any way I might be of help?

**Comment by domenkozar** [comment]
It's in my calendar for 21st January.

**Comment by domenkozar** [comment]
Life has been a bit of a pain lately, but I have not given up on this :)

**Comment by grahamc** [comment]
👀

**Comment by Baughn** [comment]
You're literally leaving money on the floor. :p

**Comment by domenkozar** [comment]
It's better now. One thing to note is that I'll create a report for donations and describe for what money is used, we don't have a good report for spending yet.

**Comment by domenkozar** [comment]
@rbvermaa is working on spending data, I have started work on the reports.

**Comment by aflatter** [comment]
😶 I'm still interested in this and more generally would love to hear about what the foundation is doing.

**Comment by Baughn** [comment]
I'm a little worried. It seems like there aren't enough core members to handle everything that needs doing.

**Comment by grahamc** [comment]
@rbvermaa added a chart to nixos.org of donations: https://nixos.org/nixos/foundation.html but unfortunately not spending. I think the foundation largely spends on a few hetzner machines for Hydra, but I don't know.

**Comment by grahamc** [comment]
Regarding "core members," two things:

1. You're probably right, but note there aren't really "defined" core members. Many/most of the people perceived as "core" are just regulars who can be counted on to do things... not actually recognized as such. I think this structure is a bit challenging for greater org things, like funding reports :)

2. I've been researching applying to have NixOS move to be under the software freedom conservancy. Unofficially. I think there is some interest in this from other people in the NixOS community too. 

Successfully doing #2 means solving #1 though.

NixOS is growing like crazy, we need to transition to a bigger model of working now, I think.

**Comment by Profpatsch** [comment]
I would recommend working with https://techcultivation.org/.
They don’t (yet) have a shiny “Patreon-like” frontend for small donations, but a team of experts with a solid understanding of and excellent connections into the FOSS community. Plus, they know how to work with official funding (e.g. they have grant projects through the EU and the Ford Foundation, and organized several projects with the Prototype Fund).

They are a German non-profit company and have been [certified as “equivalent to a U.S. public charity”](https://twitter.com/techcultivation/status/1057756534200066049) recently, which means they are allowed to issue donation receipts. 

There is a meeting weekend in Berlin this week, and I’m going to investigate whether collaborating with the NixOS Foundation is possible from their side.

Disclaimer: I’m good friends with one of their chairs, and have worked for them part-time in the past.

**Comment by domenkozar** [comment]
Seems like they are still in development mode while open collective already has what we need to accept donations, so what's the benefit for waiting? :)

**Comment by Profpatsch** [comment]
I don’t know Open Collective well enough to tell you the difference, but I’ll report back here once I’ve talked to TC.

**Comment by domenkozar** [comment]
![2018-11-02-184020_710x310_scrot](https://user-images.githubusercontent.com/126339/47934258-c97f6a00-dece-11e8-8fac-7b28fa662c35.png)

**Comment by Profpatsch** [comment]
Okay, from a short talk with one of the techcultivation.org chairs: At the moment they don’t have the capacity to take the NixOS foundation, but he’d love to work with us once they are set up.

OpenCollective and TC are *not* exclusive to each other, the services of both can be useful. For example, private donations could be handled by OC and stuff like long-time funding, payment of developers, and legal advice by TC.

**Comment by domenkozar** [comment]
Cool :) I don't know how to proceed here, but would like to give OC a shot for donations.

PS: There are projects that pay developers full time via OC.

**Comment by zimbatm** [comment]
@domenkozar what is it that you want to fund? OC could be created for the security team independently of the foundation

**Comment by domenkozar** [comment]
For now I'd limit the fund to:

- infrastructure costs (hardware, internet bills)
- funding of community events (meetups, sprints, etc)

We can expand that scope later on. There are some specific rules to be laid out how someone can claim reimbursement of expenses for an event.

**Comment by davidak** [comment]
When we would join SFC/SPI/..., they would do this work, right? https://github.com/NixOS/nixos-foundation/issues/3

**Comment by domenkozar** [comment]
I suggest we close this as NixOS is now part of Open Collective: http://opencollective.com/nixos

OC is in active development, so they'll keep adding new donation methods while keeping transparency.
