### ISSUE TITLE
Figure out NixCon VAT

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-foundation#10]
Two issues:

* We probably need to pay VAT in France for the tickets.
* And we need to pay VAT for the sponsors, probably also in France.

So we probably need to register with the French tax authorities and pay VAT for 2022.

@armijnhemel is going to ask his tax advisor about this.

**Comment by armijnhemel** [comment]
Sent mail to my accountant:

```
hallo Sander, Sjacco,

op dit moment zit ik in het bestuur van een stichting. Binnenkort gaat er een conferentie georganiseerd worden door deze stichting in Frankrijk. Voor deze conferentie gaan kaartjes verkocht worden (op dit moment nog niet, want we weten nog niet hoe het gaat met de BTW) aan individuen en zijn er ook bedrijfssponsors. Nu las ik dat dit voor de BTW kan betekenen dat er in Frankrijk BTW afgedragen moet worden en er een registratie in Frankrijk gedaan moet worden en de BTW niet verlegd kan worden naar Nederland, zoals besloten door het Hof van Justitie van de Europese Unie:

https://www.pwc.nl/nl/actueel-en-publicaties/belastingnieuws/btw/organisator-educatief-congres-btw-verschuldigd-in-eu-land-waar-dit-plaatsvindt.html

Mijn vraag: kunnen jullie helpen om te zorgen dat het allemaal netjes verloopt (zowel voor verkoop kaartjes aan invididuen, als sponsors)? Zo ja, hoeveel moeite/kosten zouden hieraan verbonden zijn? Zo nee, wie zouden jullie aanraden?

met vriendelijke groet,

armijn 
```

**Comment by armijnhemel** [comment]
Hoi Armijn,

De inhoud die je opgenomen hebt etc. is correct. Bij een andere klant hebben wij hier ook bij geholpen, dus we weten er wel voldoende over inhoudelijk. Maar dat ging in dat geval wel over een congres in Nederland (met buitenlandse bezoekers).
De advisering van ons daarbij ging bijvoorbeeld over de wijze van factureren (vanuit Nederland) aan congresbezoekers in het buitenland (en dan ook particulieren en bedrijven).

Het moet gezegd dat wij als Nederlandse fiscalisten alleen kunnen adviseren over de Nederlandse wetgeving (of belastingverdragen).

Normaal gesproken hanteert Frankrijk precies dezelfde Europees opgelegde wetgeving als die van Nederland. Maar dat is niet altijd het geval. Een Franse adviseur zal dus geraadpleegd moeten worden over de regels ter plaatse en de wijze hoe de Franse belastingdienst één en ander beschouwd en verwerkt wil hebben. Is er vanuit de stichting iemand die goede contacten heeft om dat in Frankrijk na te laten vragen?

De andere klant van ons werd, naar volle tevredenheid, bijgestaan door Anke Peters van deCongresbalie. https://decongresbalie.nl/
Dit zag bijvoorbeeld ook op de manier van verkoop van de kaartjes etc. zoals jij hieronder vraagt.
Voor zover ik weet heeft zij ook wel wat internationale contacten. Het kan dus zinvol zijn om haar te vragen om jullie bij te staan of na te vragen of zij een Franse conculega heeft die kan helpen met de in Frankrijk te volgen route qua verplichtingen etc.
Dit kunnen wij ook wel voor je doen overigens. Maar misschien kun je mij dan iets meer informatie over het congres geven. Bijvoorbeeld het aantal deelnemers, hoeveel dagen, etc.

Hopelijk heb je hier iets aan.

Als er nog vragen zijn, dan hoor ik het graag.

Met vriendelijke groet,

Sander van Mourik

**Comment by armijnhemel** [comment]
Looked into this and it seems that this cannot be solved easily in time before NixCon.

**Comment by RaitoBezarius** [comment]
Just answered Ron directly over Matrix, but I can comment here, FWIW.

# First solution : NixOS Foundation registers itself

So, yes, NixOS Foundation needs to register to French tax authorities, but to be fair, it has not to be registered *before* collecting money or doing stuff, it can just collect the VAT and put it in some safe place, wait for French tax authority heads-up and send it their way.

From my understanding, this is possible without any penalty as long as good faith is involved.

# Second solution : NixOS Foundation mandates a French non-profit ("loi 1901") to do NixCon

- NixOS Foundation receives foreign sponsoring : no French VAT.
- French non-profit receives French sponsoring : VAT-exempted due to non-profit status.
- French non-profit ask for payment to NixOS Foundation for NixCon : VAT-exempted due to non-profit status (as long as it is under 40-50K EUR IIRC.)
- French non-profit pays for event : VAT when paying for-profit organizations, VAT-exempted when paying non-profit organizations IIRC.

It requires some paperwork to have a proper contract though, but I heard this was what some other conferences have done.

# Third solution : NixOS Foundation mandates a French company to do NixCon

VAT must be paid, but everything is simplified.
Problem: finding such a company.

---

If you need more info or a quick call, I can definitely help on this as I am the French rep for the NixCon organization team.

**Comment by armijnhemel** [comment]
> Just answered Ron directly over Matrix, but I can comment here, FWIW.
> ### First solution : NixOS Foundation registers itself
> 
> So, yes, NixOS Foundation needs to register to French tax authorities, but to be fair, it has not to be registered _before_ collecting money or doing stuff, it can just collect the VAT and put it in some safe place, wait for French tax authority heads-up and send it their way.
> 
> From my understanding, this is possible without any penalty as long as good faith is involved.
> ### Second solution : NixOS Foundation mandates a French non-profit ("loi 1901") to do NixCon
> 
>     * NixOS Foundation receives foreign sponsoring : no French VAT.
> 
>     * French non-profit receives French sponsoring : VAT-exempted due to non-profit status.
> 
>     * French non-profit ask for payment to NixOS Foundation for NixCon : VAT-exempted due to non-profit status (as long as it is under 40-50K EUR IIRC.)
> 
>     * French non-profit pays for event : VAT when paying for-profit organizations, VAT-exempted when paying non-profit organizations IIRC.
> 
> 
> It requires some paperwork to have a proper contract though, but I heard this was what some other conferences have done. But actually, I am treasurer in a such a non-profit, related to ENS (where we may end up doing the NixCon): https://www.journal-officiel.gouv.fr/pages/associations-detail-annonce/?q.id=id:202200201748 (we heavily do Nix/NixOS stuff if not everything.)
> ### Third solution : NixOS Foundation mandates a French company to do NixCon
> 
> VAT must be paid, but everything is simplified. Problem: finding such a company.
> 
> If you need more info or a quick call, I can definitely help on this as I am the French rep for the NixCon organization team.

The second or third solution are the preferred ones.

**Comment by refroni** [comment]
This is great and agreed with Armijn.

**Comment by refroni** [comment]
Logging another solution - 
Open Collective Europe, it seems they can handle the fiscal hosting for NixCon. All funds will be held in the Open Collective account, which we will then be able to reimburse for NixCon expenses. 
They will charge a 6% fee.
https://opencollective.com/europe

**Comment by edolstra** [comment]
For this year, we have done this via a French org. Maybe for next year, we should figure out how the NixOS Foundation can do this itself.
