### ISSUE TITLE
NixCon 2023

### ISSUE THREAD

**Issue by domenkozar** [NixOS/nixos-foundation#17]
Pick a location and start the team.

**Comment by fricklerhandwerk** [comment]
@AlexeiDrake @BryanHonof

**Comment by zimbatm** [comment]
I would prefer if the foundation was just for support and let the nixcon team drive this.

**Comment by zimbatm** [comment]
We have a location and are waiting on #22 before making an announcement.

**Comment by softinio** [comment]
What's everyone's thoughts on running two NixCon events in 2023, 6 months a part, one in Europe and one in USA? 

I would be interested and happy to volunteer to help to organize the USA one if located in San Francisco/Silicon Valley? 

I have a lot of experience organizing meetup events for over 6 years and recently set up [Silicon Valley Nix / NixOS User Group](https://www.svnix.com). 

If curious about other meetups I have organized see [this](https://www.softinio.com/resume/#other-accomplishments).

I have also done talks at conferences and help with introducing speakers at conferences too.

Thanks.

**Comment by zimbatm** [comment]
Hi @softinio,

sounds good. We ask organizers to help with the year before, so that they can learn how we do things and keep the conference in a similar spirit. So if you are willing to do so, I think NixCon US 2024 could become a thing.

**Comment by softinio** [comment]
@zimbatm I won't be able to travel out to europe for NixCon 2023, but happy to help remotely if at all possible or needed.

If that is a blocker hopefully someone else based in the USA can step up and help. 

FYI ... being organizer not important to me, having a USA event that I can attend is my main goal with making the suggestion. Wonder if anyone who helped with NixCon 2022 is based in USA and would be happy to organize US one for 2023.

cc @refroni @fzakaria

**Comment by addict3d** [comment]
@softinio I'm based in the USA and would like to see a NixCon here eventually.

However, having experienced the time crunch and logistical challenges organizing NixCon 2020*, I'd prefer to work towards stability and solidifying processes for 2023 and beyond (i.e. [following @zimbatm thread](https://github.com/NixOS/nixos-foundation/issues/17#issuecomment-1310226673)).

*--and '20 was online-only, so considerably fewer planning tasks than Paris this year. It makes NixCon 2022 all the more impressive. Mad props and thanks to all the organizers who put it on this year!

**Comment by refroni** [comment]
I'll definitely be attending and helping wherever I can just let me know :)

**Comment by zimbatm** [comment]
Closing as the NixCon 2023 team is up and running. We'll have follow-up tickets.
