### ISSUE TITLE
Establish a Cloudflare Pages account at the Foundation level

### ISSUE THREAD

**Issue by lucperkins** [NixOS/nixos-foundation#18]
At the moment, [nix.dev](https://github.com/nixos/nix.dev) uses [Domen](https://github.com/domenkozar)'s personal [CloudFlare Pages](https://pages.cloudflare.com) account for publishing the site. As nix.dev is currently a semi-official information outlet under the Foundation, it would be best to have an account managed by the Foundation instead.

The practical issue that brought this up is that nix.dev doesn't currently have per-pull-request deploy previews, which is a feature provided by CloudFlare Pages. Some members of the Nix docs team (including myself) would like to see that enabled and would currently need to go through Domen for that. Nothing against the lovely Domen, of course, but a Foundation-level account would enable us to distribute admin capabilities across select members of the Foundation/docs team.

In terms of cost, the free plan would likely suffice to begin with. In the event that a higher plan is needed, multiple projects could likely be covered by a pro plan simultaneously.

<img width="972" alt="image" src="https://user-images.githubusercontent.com/1523104/197768998-d7826bdc-1132-4dbb-a9aa-089d198b8235.png">

**Comment by zimbatm** [comment]
This is something the NixOS Infra team should handle; to consolidate the various accounts. And the NixOS Foundation would provide the payment and funds for that hosting if necessary.

**Comment by lucperkins** [comment]
@zimbatm Is the [`nixos-org-configuration`](https://github.com/NixOS/nixos-org-configurations) repo the right place for that? That's where my very off-the-cuff Googling led me 😄

**Comment by lucperkins** [comment]
Closing, as I've moved this issue to a more relevant repo
