### ISSUE TITLE
GitHub donate button

### ISSUE THREAD

**Issue by fricklerhandwerk** [NixOS/nixos-foundation#19]
Add a convenient way for people to give the NixOS foundation money.

**Comment by zimbatm** [comment]
Which place are you thinking of? We have the donate button on each repo:
![image](https://user-images.githubusercontent.com/3248/197996561-844de238-7788-4833-9df1-1a06f598ad7b.png)

**Comment by fricklerhandwerk** [comment]
Yes, sorry for spamming.

**Comment by zimbatm** [comment]
It's not spamming. If you didn't see the donate button, it signals that it's not visible enough. What places were you expecting it to be?

**Comment by fricklerhandwerk** [comment]
It's not visible in GitHub's mobile view, but this is not our fault or problem. One way to work around this would be to use a banner or badge in the README.

nixos.org has a clearly visible Donate section, and while it could be restructured to emphasize the actionable information, one could link there.

But again, all the information is already there, so this is probably a non-issue.
