### ISSUE TITLE
Create web page / form for applying for foundation funding

### ISSUE THREAD

**Issue by edolstra** [NixOS/nixos-foundation#20]

**Comment by zimbatm** [comment]
https://opencollective.com/nixos/expenses/new ?

**Comment by domenkozar** [comment]
Create a blog post explaining what this is all about.

Add a link to the form on the website.

**Comment by mightyiam** [comment]
In the mean time, I'd like to apply to funding. Who do I contact, please?

**Comment by domenkozar** [comment]
Hey @mightyiam, this needs a few more weeks before it's ready.

**Comment by domenkozar** [comment]
See https://github.com/NixOS/nixos-homepage/pull/990

**Comment by domenkozar** [comment]
https://discourse.nixos.org/t/nix-event-funding/26154
