### ISSUE TITLE
Offering services for NixCon and other events

### ISSUE THREAD

**Issue by zimbatm** [NixOS/nixos-foundation#22]
I want to figure out how we could better use the foundation for NixCon. And hopefully be able to re-use that work for other events like Ocean Sprint, Nix Camp, ...

Having a framework like that in place is a requirement for NixCon 2023 to happen. We need to have something in place before the end of February so we have enough time to book the event, ...

## Problem statement

Events require money to function (sorry to be crude). On the input, you typically have sponsors and tickets. On the output; venue, catering, swag, AV equipment, ...

The foundation is a financial vehicle registered in NL and that can be used to fund various efforts (and people?).

How can we make those work together to:
* promote more Nix-related events by reducing the financial overheads
* funnel excess profit from sponsors back to the foundation
* improve the transparency around event costs, ...

## Naive first proposal

The NixOS Foundation would provide a form that event organizers have to fill, with some required information like location, organizers, ...

The NixOS Foundation would provide the Pretix platform, pre-configured with a Stripe account, to provide ticket sales. I'm assuming we want to use the hosted Pretix version so that some of the proceedings maintain that valuable software and don't have to burden the infra team.

The NixOS Foundation would send invoices to sponsors that agree to fund a specific event.

The NixOS Foundation would handle the invoices to pay for the venue, ...

For any events smaller than 100.- EUR (something that can pay pizzas and beer) and that happens less than 12 times per year for a given region; the foundation would only require minimal inputs.

For larger events, the organizers would be responsible for finding the sponsors (although the foundation can help communicate with/provide repeat sponsors).

TODO: How to deal with insurance?

TODO: How to deal with VAT? (see #10)

TODO: Should we hire a temp. secretary?

**Comment by bryanhonof** [comment]
> The NixOS Foundation would provide the Pretix platform, pre-configured with a Stripe account, to provide ticket sales.

Perhaps we'd also want a hosted [pretalx](https://pretalx.com/p/about/) for CfPs, and [venueless](https://venueless.org/en/) for streaming events, together with [pretix](https://pretix.eu/about/en/).


> For any events smaller than 100.- EUR (something that can pay pizzas and beer) and that happens less than 12 times per year for a given region; the foundation would only require minimal inputs.

Perhaps this is best done through [Open Collective's expense feature](https://docs.opencollective.com/help/collectives/expenses)?


-----

I'd also like to see a checklist somewhere on “how to run a successful event”. This would be a small document full of tips. E.g., during NixCon 2023 I had never imagined A/V to take so much of my time. Had I known that in advance, I'd have tried and get an A/V team together. So, the tip here could be: “You should have someone, or a team, dedicated to A/V”. I'd rather not see that turn into a procedure, but rather recommendations you *can* follow. What do you think?

**Comment by refroni** [comment]
Agreed with this and plus one on Domen's comment. This is one of the top priorities moving forward.
Regarding NixCon, this year we were able to make it possible to organize all sponsorships through the foundation.
Bigger item I would like to verify as early as possible as tax/vat for ticket sales as this might require more work.

**Comment by flokli** [comment]
I was under the impression iff the foundation would handle the ticket sales, it would charge dutch VAT when selling tickets to individuals, independently to where Nixcon itself will happen (at least inside EU), and most of the complications were due to local entities that had to handle ticket sales 🤔

Very curious about your findings, looking forward to reading them!

**Comment by armijnhemel** [comment]
> I was under the impression iff the foundation would handle the ticket sales, it would charge dutch VAT when selling tickets to individuals, independently to where Nixcon itself will happen (at least inside EU), and most of the complications were due to local entities that had to handle ticket sales

Only under certain circumstances would we be able to charge Dutch VAT for ticket sales for an event in another EU country using the so called "one stop shop" mechanism. We looked into this but in the best case we would only have been able to start ticket sales two weeks before NixCon 2022.

> Very curious about your findings, looking forward to reading them!

Search for "c-647/17 srf konsulterna ab" if you are fine reading court documents.

**Comment by armijnhemel** [comment]
> > Very curious about your findings, looking forward to reading them!
> 
> Search for "c-647/17 srf konsulterna ab" if you are fine reading court documents.

https://www.vatupdate.com/2019/03/14/ecj-case-c%E2%80%91647-17-srf-konsulterna-judgment-admission-to-educational-events-place-of-supply/

```
It follows that the place where courses such as those at issue in the main proceedings are deemed to be supplied must be determined on the basis of Article 53 of the VAT Directive, and those courses must, consequently, be subject to VAT in the place where the services are actually supplied, that is in the Member States where those courses are given.
```

**Comment by armijnhemel** [comment]
> https://eclear.com/topic/one-stop-shop/ describes the two concepts (conventional and one stop). Only having to declare VAT in .NL, rather than in every state where a Nix education event might be happening sounds desirable in general.
> 
> Would the foundation qualify for One Stop Shop mechanism? Did you continue with that application process, or was it shelved for now?

We did not register, because it would not have made sense because there simply was not enough time before NixCon 2022 and it would also have meant an additional administrative burden (explained below), while we would not have been able to use the "one stop shop". So this didn't make sense to us.

If we would qualify: perhaps, if we would keep our turnover inside the EU < 10,000 EUR (the Dutch tax office isn't clear if this is < or <= ). This would likely mean ticket sales and EU sponsoring combined (as sponsors get an invoice).

There is also quite a bit of extra administration involved: you need to declare everything every quarter, even if you didn't "sell" anything. If you don't do this properly or forget it, you are barred from the system from two years.

**Comment by flokli** [comment]
The 10k EUR is independent of whether one stop shop is used or not. It simply makes the reporting easier, because it's one centralized interface.

**Comment by armijnhemel** [comment]
> The 10k EUR is independent of whether one stop shop is used or not. It simply makes the reporting easier, because it's one centralized interface.

No, that is not what the Dutch tax office says. If it is more than 10k EUR you cannot use the one stop shop but have to register locally.

**Comment by flokli** [comment]
I don't fully understand dutch, but I think what I google-translated doesn't seem to contradict what I understood:

For > 10k turnover, VAT needs to be declared/paid in the member state. This is independently of whether you're registered for One Stop Shop or not.

Being registered for One-Stop will make things easier however, because you don't need to manually register in each other member state to pay VAT there, but instead you declare/pay it in one central portal of your "home country" and the home country takes care of the clearing / distributing of collected VAT to other member states.

Again, that's how I understood it - I'm no accountant - please consult one ;-)

But I think having the foundation set up to do these larger-scale events in all of EU is very worth the additional research.

**Comment by armijnhemel** [comment]
> I don't fully understand dutch, but I think what I google-translated doesn't seem to contradict what I understood:
> 
> For > 10k turnover, VAT needs to be declared/paid in the member state. This is independently of whether you're registered for One Stop Shop or not.
> 
> Being registered for One-Stop will make things easier however, because you don't need to manually register in each other member state to pay VAT there, but instead you declare/pay it in one central portal of your "home country" and the home country takes care of the clearing / distributing of collected VAT to other member states.
> 
> Again, that's how I understood it - I'm no accountant - please consult one ;-)
> 
> But I think having the foundation set up to do these larger-scale events in all of EU is very worth the additional research.

I looked a bit further (clicked on a few additional links with more information) and it seems that you are correct. I will put it on the TODO for the board. Last time we didn't look that deep into it because we were so close to NixCon.

**Comment by zimbatm** [comment]
The NixCon team has been blocked from booking and announcing the location and making progress since November.

**Comment by zimbatm** [comment]
Quick update: we had a meeting on Monday evening, and this was largely resolved I believe. The NixOS Foundation told me they will register for VATMOSS to sell tickets. I also registered a NixCon OpenCollective so we can have a backup fiscal host.

**Comment by andir** [comment]
> Quick update: we had a meeting on Monday evening, and this was largely resolved I believe. The NixOS Foundation told me they will register for VATMOSS to sell tickets. I also registered a NixCon OpenCollective so we can have a backup fiscal host.

@NixOS/board-members is this the final response to this ticket? Can you acknowledge what Jonas said?

**Comment by edolstra** [comment]
Yes, we are registered, see https://github.com/NixOS/nixos-foundation/issues/30.

**Comment by zimbatm** [comment]
I'm now satisfied with the state of things:

* the Foundation is VAT-MOSS registered
* you can now use the event funding form to connect with the NixOS Foundation: https://discourse.nixos.org/t/nix-event-funding/26154

I will create a separate ticket for Pretix
