### ISSUE TITLE
Spending Request: Upgrades to the the macOS builders

### ISSUE THREAD

**Issue by grahamc** [NixOS/nixos-foundation#5]
# What I want to spend money on

In short, I propose we buy 9x Samsung 860 EVO 250GB hard drives (none of the macOS builders use more than 100G.)

I also propose upgrading mac1 from 4G of RAM to 8G of DDR3L 1600 (PC3L 12800), which matches the other mac builders.

# How much it will cost

| what | cost | quantity |  link |
|-|-|-|-|
| Samsung 860 EVO 250GB | $60 | 9 | https://www.newegg.com/samsung-860-evo-series-250gb/p/N82E16820147676 |
| 8G of DDR3L 1600 (PC3L 12800) (2x4GB)| $52 | 1 | https://www.newegg.com/crucial-8gb-204-pin-ddr3-so-dimm/p/N82E16820148608 |
| Mac Mini Logic Board Removal Tool | $5 | 1 | https://www.ifixit.com/Store/Tools/Mac-mini-Logic-Board-Removal-Tool/IF145-159?o=3 |
| iFixit Tool Kit | $60 | 1 | https://www.ifixit.com/Store/Tools/Pro-Tech-Toolkit/IF145-307?o=4 |

Total: $680

(Note: the iFixIt tool kit contains all the tools we need and more, plus a case to put them all in.)

# Why

I was curious why our macs are so slow to use interactively. It didn't take me long to find some answers.

Passmark says this about our current drives and my proposed drive:

![image](https://user-images.githubusercontent.com/76716/63290196-ebe04980-c28e-11e9-91ef-3fbac6035e0b.png)

# Background

Some info about our hardware:

- mac1 is a Macmini6,1 https://support.apple.com/kb/SP659?locale=en_US
- mac2-8 are Macmini7,1 https://support.apple.com/kb/SP710?locale=en_US
- all the machines use less than 100G of disk space
- all the disks are 5400rpm
- the machines are a mix of SATA, SATA 2.6, and SATA3

# Implementation

I will bug and bother @rbvermaa until he does it. Also, I will link him to these three helpful guides:

 - mac1 RAM: https://www.ifixit.com/Guide/Mac+mini+Late+2012+RAM+Replacement/11726
 - mac1 Disk: https://www.ifixit.com/Guide/Mac+mini+Late+2012+Hard+Drive+Replacement/11716
 - mac2-8 Disk: https://www.ifixit.com/Guide/Mac+mini+Late+2014+Hard+Drive+Replacement/32815

## mac1
```
00:1f.2 SATA controller: Intel Corporation 7 Series Chipset Family 6-port SATA Controller [AHCI mode] (rev 04)
Model name:          Intel(R) Core(TM) i5-3210M CPU @ 2.50GHz

              total        used        free      shared  buff/cache   available
Mem:              3           3           0           0           0           0
Swap:            15           0          15

```

## mac2-mac8
```
00:1f.2 SATA controller: Intel Corporation 8 Series SATA Controller 1 [AHCI mode] (rev 04)
Model name:          Intel(R) Core(TM) i5-4278U CPU @ 2.60GHz

              total        used        free      shared  buff/cache   available
Mem:              7           6           0           0           0           0
Swap:            15           0          15
```

## mac1
```
=== START OF INFORMATION SECTION ===
Model Family:     Hitachi/HGST Travelstar Z5K500
Device Model:     APPLE HDD HTS545050A7E362
Serial Number:    TEG5193RKSDAJG
User Capacity:    500,107,862,016 bytes [500 GB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac2
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    JD8002D82KZSGD
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac3
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    JD8002D82L08DD
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac4
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    JD8002D82D1TVD
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac5
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    JD8008D828X4XS
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac6
```

=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD ST1000LM024
Serial Number:    S35RJ9DGA08673
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac7
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    JD8002D801SJGD
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

## mac8
```
=== START OF INFORMATION SECTION ===
Device Model:     APPLE HDD HTS541010A9E662
Serial Number:    J88000D80AAJ6B
User Capacity:    1,000,204,886,016 bytes [1.00 TB]
Sector Sizes:     512 bytes logical, 4096 bytes physical
Rotation Rate:    5400 rpm
Form Factor:      2.5 inches
```

**Comment by rbvermaa** [comment]
Seems like a good idea. I will order the hardware, and once I have moved the macmini's to the new location, replace the hardware.

**Comment by rbvermaa** [comment]
https://opencollective.com/nixos/expenses/9658

**Comment by rbvermaa** [comment]
Hardware arrived, will install once I get the mac mini's in the new location.

**Comment by rbvermaa** [comment]
Internet connection at the new location has been installed, 500bmit up/down. Will move the mac's later this week.

**Comment by rbvermaa** [comment]
All hardware has been installed and they have been bootstrapped with nixos. @grahamc will adopt them in the buildfarm again. Also managed to get mac9 working again. Closing the issue.

**Comment by grahamc** [comment]
(mac1 is absent because I disabled SSH on it by mistake, after Rob wasn't around to roll back :'))

upgraded stats on these machines:

### mac2
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691682T
    LU WWN Device Id: 5 002538 e49667565
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:01:54 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           1           1
    Swap:            15           0          15

### mac3
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691671V
    LU WWN Device Id: 5 002538 e4966750f
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:01:55 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           0           1
    Swap:            15           0          15

### mac4
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691648B
    LU WWN Device Id: 5 002538 e496674da
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:01:57 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           1           1
    Swap:            15           0          15

### mac5
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691667X
    LU WWN Device Id: 5 002538 e4966750b
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:01:59 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           1           0           0           1
    Swap:            15           0          15

### mac6
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M684637A
    LU WWN Device Id: 5 002538 e4966375a
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:02:00 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           0           0
    Swap:            15           0          15

### mac7
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691668D
    LU WWN Device Id: 5 002538 e4966750c
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:02:02 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           0           0
    Swap:            15           0          15

### mac8
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M691647K
    LU WWN Device Id: 5 002538 e496674d9
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:02:04 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           6           0           0           1           1
    Swap:            15           0          15

### mac9
    smartctl 7.0 2018-12-30 r4883 [x86_64-linux-4.19.69] (local build)
    Copyright (C) 2002-18, Bruce Allen, Christian Franke, www.smartmontools.org

    === START OF INFORMATION SECTION ===
    Model Family:     Samsung based SSDs
    Device Model:     Samsung SSD 860 EVO 250GB
    Serial Number:    S3YJNX0M684639Z
    LU WWN Device Id: 5 002538 e4966375c
    Firmware Version: RVT03B6Q
    User Capacity:    250,059,350,016 bytes [250 GB]
    Sector Size:      512 bytes logical/physical
    Rotation Rate:    Solid State Device
    Form Factor:      2.5 inches
    Device is:        In smartctl database [for details use: -P show]
    ATA Version is:   ACS-4 T13/BSR INCITS 529 revision 5
    SATA Version is:  SATA 3.2, 6.0 Gb/s (current: 6.0 Gb/s)
    Local Time is:    Sat Sep 28 21:02:06 2019 UTC
    SMART support is: Available - device has SMART capability.
    SMART support is: Enabled

                  total        used        free      shared  buff/cache   available
    Mem:              7           5           0           0           1           2
    Swap:            15           0          15
